#include "aes-common.h"
#include "../global-common.h"
#include "../convolution.h"

int 
main(void)
{
	Table *correlations_sbox = table_create();
	Table *correlations_superbox = table_create();

	mpz_t row, col, val, number_of_differences;
	mpz_init(number_of_differences);

	// All rows of the correlation matrix are equal, except the first, which contains 256 followed by all zeros.
	// Insert triples (abs value of correlation numerator, log2(correlation denominator), number of masks) into the histogram of the sbox
	// These values were generated by ./aes-sbox 

	// Floor(2*(8 - log2(N))) where N is the entry in correlation table of S-box.
	// This is an approximation for ease of implementation.

	mpz_init_set_ui(col, 0);

	mpz_init_set_ui(row, 12);
	mpz_init_set_ui(val, 48);
	table_insert_and_merge(correlations_sbox, row, col, val, &mpz_add);
	mpz_set_ui(row, 10);
	mpz_set_ui(val, 36);
	table_insert_and_merge(correlations_sbox, row, col, val, &mpz_add);
	mpz_set_ui(row, 10);
	mpz_set_ui(val, 40);
	table_insert_and_merge(correlations_sbox, row, col, val, &mpz_add);
	mpz_set_ui(row, 8);
	mpz_set_ui(val, 34);
	table_insert_and_merge(correlations_sbox, row, col, val, &mpz_add);
	mpz_set_ui(row, 8);
	mpz_set_ui(val, 24);
	table_insert_and_merge(correlations_sbox, row, col, val, &mpz_add);
	mpz_set_ui(row, 8);
	mpz_set_ui(val, 36);
	table_insert_and_merge(correlations_sbox, row, col, val, &mpz_add);
	mpz_set_ui(row, 8);
	mpz_set_ui(val, 16);
	table_insert_and_merge(correlations_sbox, row, col, val, &mpz_add);
	mpz_set_ui(row, 6);
	mpz_set_ui(val, 5);
	table_insert_and_merge(correlations_sbox, row, col, val, &mpz_add);

	for (int w = 5; w <= MAX_BOX_WEIGHT; w++) {
		// The linear branch number is 5, so d = 5. Moreover, the field is GF(2^8), i.e. q = 256.
		// Finally, M is a square matrix, so the transpose has the same number of rows, i.e. n = 8.
		mds_weight_enumerator(number_of_differences, 256, 8, 5, w);
		// Convolute the histograms of all w sboxes
		Table *r = convolve_tables(correlations_sbox, w, 0, 0, differential_combiners);
		for (HeadNode *node = r->head; node != NULL; node = node->next_row) {
			mpz_mul(number_of_differences, number_of_differences, node->node.val);
			table_insert_and_merge(correlations_superbox, node->node.row, col, number_of_differences, &mpz_add);
		}
		table_destroy(r);
	}

	// Weight 0 only occurs when every sbox is inactive, which happens for exactly one trail.
	mpz_set_ui(row, 0);
	mpz_set_ui(col, 0);
	mpz_set_ui(val, 1);
	table_insert_and_merge(correlations_superbox, row, col, val, &mpz_add);

	mpz_clears(row, col, val, number_of_differences, NULL);

	table_print("data/aes-linear-trail-superbox.txt", correlations_superbox);
	// Convolute the histograms of the superboxes to get the histogram of the full state.
	Table *correlations_full = convolve_tables(correlations_superbox, NUMBER_OF_SUPERBOXES, 0, 0, differential_combiners);
	table_print("data/aes-linear-trail-full.txt", correlations_full);

	table_destroy(correlations_sbox);
	table_destroy(correlations_superbox);
	table_destroy(correlations_full);

	return 0;
}
